apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phpmyadmin-ingress
spec:
  rules:
    - host: {{ .Values.phpmyadmin.ingressHost }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: phpmyadmin
                port:
                  number: {{ .Values.phpmyadmin.port }}
