apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: {{ .Values.wordpress.image }}
          ports:
            - containerPort: {{ .Values.wordpress.port }}
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Values.mysql.image }}
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.mysql.dbName }}
            - name: WORDPRESS_DB_USER
              value: {{ .Values.mysql.dbUser }}
            - name: WORDPRESS_DB_PASSWORD
              value: {{ .Values.mysql.dbPassword }}
